import { useTranslation } from "react-i18next";

const useSummaryMetaData = () => {
  const { t } = useTranslation();
  const labels = {
    id: t("common.code"),
    code: t("common.code"),
    pex_ID: t("common.code"),
    therapyID: t("common.code"),
    date: t("common.date"),
    visitDate: t("opd.date"),
    labDate: t("lab.date"),
    opdDate: t("opd.date"),
    startDate: t("therapy.startDate"),
    endDate: t("therapy.endDate"),
    opDate: t("operation.opDate"),
    admDate: t("admission.admDate"),
    disDate: t("admission.disDate"),
    type: t("common.type"),
    admType: t("admission.admType"),
    disType: t("admission.disType"),
    ward: t("admission.ward"),
    diseaseOut1: t("admission.diseaseOut1"),
    nextAppointment: t("admission.nextAppointment"),
    operation: t("operation.operation"),
    transUnits: t("operation.transUnits"),
    remarks: t("operation.remarks"),
    prescriber: t("operation.prescriber"),
    disease: t("opd.disease1"),
    disease2: t("opd.disease2"),
    disease3: t("opd.disease3"),
    pex_date: t("examination.datetriage"),
    pex_height: t("examination.height"),
    pex_weight: t("examination.weight"),
    pex_ap_max: t("examination.ap.max"),
    pex_ap_min: t("examination.ap.min"),
    pex_temp: t("examination.temperature"),
    pex_sat: t("examination.saturation"),
    pex_diuresis: t("examination.diuresisvolume24h"),
    pex_rr: t("examination.respiratoryrate"),
    pex_hr: t("examination.heartrate"),
    pex_hgt: t("examination.hgt"),
    pex_diuresis_desc: t("examination.diuresis"),
    pex_bowel_desc: t("examination.bowel"),
    pex_auscultation: t("examination.auscultation"),
    pex_note: t("examination.note"),
    pex_body_mass_index: t("examination.bodymassindex"),
    pex_branchial_perimeter: t("examination.branchialperimeter"),
    pex_ipt: t("examination.ipt"),
    pex_pc: t("examination.headcircumference"),
    pex_head_circ_age: t("examination.headcircumferencescore"),
    pex_weight_age: t("examination.weightscore"),
    pex_height_age: t("examination.heightscore"),
    pex_body_mass_index_age: t("examination.bodymassindexscore"),
    exam: t("lab.exam"),
    result: t("lab.result"),
    qty: t("therapy.quantity"),
    freqInDay: t("therapy.frequencyInDay"),
    freqInPeriod: t("therapy.frequencyInPeriod"),
    note: t("therapy.note"),
    medicalId: t("therapy.medical"),
    service: t("visit.service"),
    duration: t("visit.duration"),
    performedAt: t("conditioning.performedAt"),
    ventilation: t("conditioning.ventilation"),
    oxygenDebit: t("conditioning.oxygenDebit"),
    sgVolume: t("conditioning.sgVolume"),
    diazepamDose: t("conditioning.diazepamDose"),
    bolusSsVolume: t("conditioning.bolusSsVolume"),
    sngNumber: t("conditioning.sngNumber"),
    reheating: t("conditioning.reheating"),
    others: t("conditioning.others"),
    hivTest: t("conditioning.hivTest"),
    malaria: t("conditioning.malaria"),
    careDate: t("care.careDate"),
    plannedCare: t("care.plannedCare"),
    observation: t("care.observation"),
    team: t("care.team"),
    siblingRank: t("medicalHistory.physiological.siblingRank"),
    termPregnancy: t("medicalHistory.physiological.pregnancyTerm"),
    pregnancy: t("medicalHistory.physiological.pregnancy"),
    deliveryMode: t("medicalHistory.physiological.deliveryMode"),
    reasonMode: t("medicalHistory.physiological.reasonMode"),
    apgarScore: t("medicalHistory.physiological.apgarScore"),
    birthWeight: t("medicalHistory.physiological.birthWeight"),
    vaccinationStatePev: t("medicalHistory.physiological.vaccinationStatePev"),
    vaccinationStateNoPev: t("medicalHistory.physiological.vaccinationStateNoPev"),
    antiMalarialProphylaxisMilda: t("medicalHistory.physiological.antiMalarialProphylaxisMilda"),
    antiMalarialProphylaxisVap: t("medicalHistory.physiological.antiMalarialProphylaxisVap"),
    antiMalarialProphylaxisOthers: t("medicalHistory.physiological.antiMalarialProphylaxisOthers"),
    surgicalProcedure: t("medicalHistory.personalPathological.surgicalProcedure"),
    surgicalProcedureCondition: t("medicalHistory.personalPathological.surgicalProcedureCondition"),
    surgicalProcedureType: t("medicalHistory.personalPathological.surgicalProcedureType"),
    surgicalProcedureDate: t("medicalHistory.personalPathological.surgicalProcedureDate"),
    diversification: t("medicalHistory.physiological.diversification"),
    neonatalPeriod: t("medicalHistory.personalPathological.neonatalPeriod"),
    previousHospitalization: t("medicalHistory.personalPathological.previousHospitalization"),
    father: t("medicalHistory.familyPathological.father"),
    mother: t("medicalHistory.familyPathological.mother"),
    siblings: t("medicalHistory.familyPathological.siblings"),
    otherUsefulInformation: t("medicalHistory.familyPathological.otherUsefulInformation"),
    diet: t("medicalHistory.physiological.diet"),
    deParasitization: t("medicalHistory.physiological.deParasitization"),
    psychomotorDev: t("medicalHistory.physiological.psychomotorDevelopment"),
    somaticGrowth: t("medicalHistory.physiological.somaticGrowth"),
    ironSupplement: t("medicalHistory.physiological.ironSupplement"),
    folicAcidSupplement: t("medicalHistory.physiological.folicAcidSupplement"),
    vitASupplement: t("medicalHistory.physiological.vitASupplement"),
    otherSupplements: t("medicalHistory.physiological.otherSupplements"),
    transfusion: t("medicalHistory.personalPathological.transfusion"),
    lastTransfusionDate: t("medicalHistory.personalPathological.lastTransfusionDate"),
    sickleCell: t("medicalHistory.personalPathological.sickleCell"),
    drugAllergy: t("medicalHistory.personalPathological.drugAllergy"),
    allergyPrecision: t("medicalHistory.personalPathological.allergyPrecision"),
    hemylosis: t("medicalHistory.personalPathological.hemolysis"),
    otherPersonalPathologies: t("medicalHistory.personalPathological.otherPathologies"),
    otherFamilyPathologies: t("medicalHistory.familyPathological.otherFamilyPathologies"),
    otherPregnancySection: t("medicalHistory.physiological.otherPregnancySection"),
    otherVaccinationStateSection: t("medicalHistory.physiological.otherVaccinationStateSection"),
    combinedBreastfeeding: t("medicalHistory.physiological.combinedBreastfeeding"),
    noApplicableDeparasitation: t("medicalHistory.physiological.noApplicableDeparasitation"),
  };
  
  const dateFields = [
    "date",
    "admDate",
    "disDate",
    "opDate",
    "visitDate",
    "pex_date",
    "startDate",
    "endDate",
    "labDate",
    "performedAt",
    "careDate",
    "lastTransfusionDate",
    "surgicalProcedureDate",
  ];
  const header = {
    date: ["date", "type"],
    type: {
      opd: ["date", "disease"],
      triage: ["date", "pex_temp"],
      exam: ["date", "exam"],
      admission: ["date", "admType"],
      operation: ["date", "operation"],
      therapy: ["date", "medicalId"],
      visit: ["date", "duration"],
      conditioning: ["date", "type"],
      care: ["careDate", "plannedCare"],
      medicalHistory: ["performedAt", "siblingRank"],
    },
  };
  const order = ["date", "type"];

  return { labels, dateFields, header, order };
};

export default useSummaryMetaData;
