import { ApiResponse } from "state/types";
import { IPharmacyState } from "./types";

export const initial: IPharmacyState = {
  wardMovements: new ApiResponse({ status: "IDLE", data: [] }),
  wardMedicals: new ApiResponse({ status: "IDLE", data: [] }),
  getCurrentQuantityInWard: {} as Record<string, ApiResponse<number> | undefined>,
  movementTypes: new ApiResponse({ status: "IDLE", data: [] }),
  getMovements: new ApiResponse({ status: "IDLE", data: [] }),
  getMovementsWard: new ApiResponse({ status: "IDLE", data: [] }),
  getWardMovementsToWard: new ApiResponse({ status: "IDLE", data: [] }),
  createMovement: new ApiResponse({ status: "IDLE" }),
  updateMovement: new ApiResponse({ status: "IDLE" }),
  deleteMovement: new ApiResponse({ status: "IDLE" }),
  chargeMovements: new ApiResponse({ status: "IDLE" }),
  dischargeMovements: new ApiResponse({ status: "IDLE" }),
  getMedicals: new ApiResponse({ status: "IDLE", data: [] }),
  getMedical: new ApiResponse({ status: "IDLE" }),
  newMedical: new ApiResponse({ status: "IDLE" }),
  updateMedical: new ApiResponse({ status: "IDLE" }),
  getMedicalTypes: new ApiResponse({ status: "IDLE", data: [] }),
  newMovementWard: new ApiResponse({ status: "IDLE" }),
  medicalLots: new ApiResponse({ status: "IDLE", data: [] }),
  wardStock: {
    filter: {
      ward: undefined,
      type: undefined,
      drugs: undefined,
      getMovements: new ApiResponse({ status: "IDLE", data: [] }),
      createMovement: new ApiResponse({ status: "IDLE" }),
      updateMovement: new ApiResponse({ status: "IDLE" }),
      deleteMovement: new ApiResponse({ status: "IDLE" }),
      getMedicals: new ApiResponse({ status: "IDLE", data: [] }),
      getMedicalsMov: new ApiResponse({ status: "IDLE", data: [] }),
    },
  },
  createWardMovement: new ApiResponse({ status: "IDLE", data: false }),
  getMedicalWardByWardMedicalAndLot: new ApiResponse({
    status: "IDLE",
  }),
  printPharmaceuticalStockWardPdf: new ApiResponse({ status: "IDLE" }),
  printPharmaceuticalStockPdf: new ApiResponse({ status: "IDLE" }),
  printPharmaceuticalStockCardPdf: new ApiResponse({ status: "IDLE" }),
  printPharmaceuticalAMCPdf: new ApiResponse({ status: "IDLE" }),
  printPharmaceuticalStockWardExcel: new ApiResponse({ status: "IDLE" }),
  printPharmaceuticalExpirationPdf: new ApiResponse({ status: "IDLE" }),
};
